<a href="https://colab.research.google.com/github/haishan-shi/A1/blob/master/Model%20Complexity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Represent_All_X_Samples.

In [0]:
def generate_all_X_space_samples():
    """
    As the function name shows,  here we want to return the 
    complete set of possible X values. The straightforward 
    implementation of the X-space is a list of tuples. Let us 
    consider a simple range: the integers from 0 to N-1, and 
    use this range for both dimensions. Say N=3, we want to 
    generate X-samples as
    [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
        (2, 0),
        (2, 1),
        (2, 2),
    ]
    
    For small N, we can explicitly write out the list, but we need 
    a program to generate such a list for arbitrary N:
    """
    
    # Let's make an empty list
    X_space = []
    
    # Study the elements in the example list, and fill up our
    # X_space, e.g. by
    X_space.append((0, 0)) # A sample in X is a tuple, so we use 
    # a pair of parentheses, i.e. the input to the "append" function
    # is "(0, 0)", not "0, 0", which will be interpreted as 2 inputs.
    X_space.append((0, 1))
    X_space.append((0, 2))
    # ... you can complete the rest if you wish, but better read on.
    # we will use smarter methods.
    
    # Last but note least, 
    return X_space

In [2]:
X_space = generate_all_X_space_samples()
print(X_space)

[(0, 0), (0, 1), (0, 2)]


In [0]:
def generate_all_X_space_samples():
    """
    We will use loops to generate the tuples!
    """
    
    # Let's make an empty list
    X_space = []
    
    # Simple observation shows the first 3 tuples are (0, j)
    # and j is running from 0 to 3 (exclusive, Python convention)
    
    # This is the perfect case to use a for-loop, so we can write the
    # list building program this way:
    
    # for j in range(3):
    #     X_space.append((0, j))
    # for j in range(3):
    #     X_space.append((1, j))
    # for j in range(3):
    #     X_space.append((2, j))
    
    # You may have noticed, the first element in each tuple in those
    # loops runs from 0 to 3 (exclusive) as well, and can also be
    # managed by a loop
    for i in range(3):
        for j in range(3):
            X_space.append((i, j))
    return X_space

In [4]:
X_space = generate_all_X_space_samples()
print(X_space)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


In [5]:

# 1. building list by appending one element each time
my_list_a = []
for i in range(5):
    my_list_a.append(i**2) # square
print("List-a of Sqr for [0, 5):", my_list_a)

# 2. Write the message above naturally as python code
my_list_b = [i**2 for i in range(5)] # Bracket [..] to construct a list
print("List-b of Sqr for [0, 5):", my_list_b)

List-a of Sqr for [0, 5): [0, 1, 4, 9, 16]
List-b of Sqr for [0, 5): [0, 1, 4, 9, 16]


In [6]:
# 3. Powerful generator
# The element object can be complex object. 
# The []-generating loop can be nested.
# The generation process can be conditioned, too.

my_list_c = [(j, j + i**2) for i in range(10)
             if i % 2 == 0
             for j in range(100, 600, 100)
             if j != 300]
print(my_list_c)

[(100, 100), (200, 200), (400, 400), (500, 500), (100, 104), (200, 204), (400, 404), (500, 504), (100, 116), (200, 216), (400, 416), (500, 516), (100, 136), (200, 236), (400, 436), (500, 536), (100, 164), (200, 264), (400, 464), (500, 564)]


In [0]:
def generate_all_X_space_samples(N):
    """
    Generate complete sample of X-space
    :param N: Discrete X-space dimension size. The size is homogeneous
      in all dimensions.
    :type N: int
    """
    
    return [(i, j) for i in range(N)
            for j in range(N)]

In [8]:

X = generate_all_X_space_samples(3)
print("There are {} samples in X-space.".format(len(X))) # {}-format
# is used to inject some information from variables to a string.
print("All samples:\n\t", X) # \n: new line, \t indent

# You can also investigate using multiple print's
for sample_id in range(len(X)): # Try to figure out the construction
    print("Sampe {}: {}".format(sample_id, X[sample_id]))
    
# You can use [:] indexing to conveniently check a subset of data samples
print("Sample 1-5 (exc):", X[1:5])
# [:End] means start from 0
print("Sample 0-3 (exc):", X[:3])
# Similarly, [Start:] means until the end
print("Sample 3-Last (inc):", X[3:])
# You can use -i (<0 index) to represent "reversing from the end"
print("Last Sample:", X[-1])
print("Sample 3-Last (exc):", X[3:-1])

There are 9 samples in X-space.
All samples:
	 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Sampe 0: (0, 0)
Sampe 1: (0, 1)
Sampe 2: (0, 2)
Sampe 3: (1, 0)
Sampe 4: (1, 1)
Sampe 5: (1, 2)
Sampe 6: (2, 0)
Sampe 7: (2, 1)
Sampe 8: (2, 2)
Sample 1-5 (exc): [(0, 1), (0, 2), (1, 0), (1, 1)]
Sample 0-3 (exc): [(0, 0), (0, 1), (0, 2)]
Sample 3-Last (inc): [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Last Sample: (2, 2)
Sample 3-Last (exc): [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1)]


In [0]:
# Let us use the numpy library
import numpy as np # the "as" is optional and to save typing

def generate_all_X_space_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    
    # Let's make an empty list
    X_space = np.zeros((N**2, 2)) # the 
    
    # Loop is similar to that in Round2
    # except that all samples are created at the
    # beginning, and we now use an index to loop over them
    index = 0
    for i in range(N):
        for j in range(N):
            X_space[index][0] = i
            X_space[index][1] = j
            index += 1
    return X_space

In [10]:
X_np = generate_all_X_space_samples_np(3)
print(X_np)
print(type(X_np)) # Note the type is a np-array
# Check out a sample
i = 3
print("An X-Sample[{}]:{}".format(i, X_np[i]))
# Check attribute-0 for all samples
j = 0
print("X-Attribute[{}]:{}".format(j, X_np[:, j]))
# [:, 0]: take from all (:) samples, the attribute-0

[[0. 0.]
 [0. 1.]
 [0. 2.]
 [1. 0.]
 [1. 1.]
 [1. 2.]
 [2. 0.]
 [2. 1.]
 [2. 2.]]
<class 'numpy.ndarray'>
An X-Sample[3]:[1. 0.]
X-Attribute[0]:[0. 0. 0. 1. 1. 1. 2. 2. 2.]


In [0]:
def scale_X_to_0_1(X, N):
    """
    Get a new list scaling the elements in X by 1/N.
    """
    new_list = []
    for x in X: # you can iterate over each element (a tuple in x)
        # now x is one data sample in X, such as (0, 2)
        new_list.append((x[0]/N, x[1]/N))
    return new_list

In [12]:
X = generate_all_X_space_samples(5)
X1 = scale_X_to_0_1(X, 5)
print(X1)

[(0.0, 0.0), (0.0, 0.2), (0.0, 0.4), (0.0, 0.6), (0.0, 0.8), (0.2, 0.0), (0.2, 0.2), (0.2, 0.4), (0.2, 0.6), (0.2, 0.8), (0.4, 0.0), (0.4, 0.2), (0.4, 0.4), (0.4, 0.6), (0.4, 0.8), (0.6, 0.0), (0.6, 0.2), (0.6, 0.4), (0.6, 0.6), (0.6, 0.8), (0.8, 0.0), (0.8, 0.2), (0.8, 0.4), (0.8, 0.6), (0.8, 0.8)]


In [13]:
# On te other hand, operating on numpy array is much easier
X_np = generate_all_X_space_samples_np(5)
X1_np = X_np/5
print(X1_np)

[[0.  0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.6]
 [0.  0.8]
 [0.2 0. ]
 [0.2 0.2]
 [0.2 0.4]
 [0.2 0.6]
 [0.2 0.8]
 [0.4 0. ]
 [0.4 0.2]
 [0.4 0.4]
 [0.4 0.6]
 [0.4 0.8]
 [0.6 0. ]
 [0.6 0.2]
 [0.6 0.4]
 [0.6 0.6]
 [0.6 0.8]
 [0.8 0. ]
 [0.8 0.2]
 [0.8 0.4]
 [0.8 0.6]
 [0.8 0.8]]


In [14]:
%timeit X1 = scale_X_to_0_1(X, 5)

100000 loops, best of 3: 6.03 µs per loop


In [15]:
%timeit X1 = X1_np = X_np/5

The slowest run took 36.85 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.15 µs per loop


In [0]:
def generate_all_X_space_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    # We will have the following for N=3
    # X0:      X1:
    # 0 1 2    0 0 0
    # 0 1 2    1 1 1
    # 0 1 2    2 2 2
    
    # X0, if "flattened", becomes
    # 0 1 2 0 1 2 0 1 2
    
    # flattened X0 and X1 if "stacked" becomes
    # [[0 1 2 0 1 2 0 1 2
    #  [0 0 0 1 1 1 2 2 2]]
    
    # The following matrix, 
    # [[a b c]
    #  [d e f]]
    # if "transposed" (numpy operator "T"), becomes
    # [[a d]
    #  [b e]
    #  [c f]]
    return np.stack([X0.flatten(), X1.flatten()]).T

In [17]:
print(generate_all_X_space_samples_np(3))

[[0 0]
 [1 0]
 [2 0]
 [0 1]
 [1 1]
 [2 1]
 [0 2]
 [1 2]
 [2 2]]


In [18]:
%timeit generate_all_X_space_samples_np(500)

The slowest run took 6.67 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 2.62 ms per loop


In [19]:
%timeit generate_all_X_space_samples(500)

10 loops, best of 3: 43.8 ms per loop


In [0]:

# Finally, we can make version that includes the normalisation 
# (1/N) in the construction
def generate_all_X_space_normalised_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    return np.stack([X0.flatten(), X1.flatten()]).T / N

In [21]:
print(generate_all_X_space_samples_np(3))

[[0 0]
 [1 0]
 [2 0]
 [0 1]
 [1 1]
 [2 1]
 [0 2]
 [1 2]
 [2 2]]


In [22]:
X = generate_all_X_space_samples(5)
X1 = scale_X_to_0_1(X, 5)
print(X1)

[(0.0, 0.0), (0.0, 0.2), (0.0, 0.4), (0.0, 0.6), (0.0, 0.8), (0.2, 0.0), (0.2, 0.2), (0.2, 0.4), (0.2, 0.6), (0.2, 0.8), (0.4, 0.0), (0.4, 0.2), (0.4, 0.4), (0.4, 0.6), (0.4, 0.8), (0.6, 0.0), (0.6, 0.2), (0.6, 0.4), (0.6, 0.6), (0.6, 0.8), (0.8, 0.0), (0.8, 0.2), (0.8, 0.4), (0.8, 0.6), (0.8, 0.8)]


# Represent all possible X-y relations

In [0]:
# Let us first prepare the X-space as discrete samples as above. 
# And before we start building all the possible X-y mappings. 
# It is sensible to have an idea about how many such 
# mappings we are going to consider.

# So here is our first attempt of making the object template 
# of the all-inclusive mapping representation.
class CompleteDiscrete2DBinaryMapping(object):
    """
    An exhaustive representation of 2D X space to binary targets.
    The 2D space is represented using discrete grid points.
    """
    def __init__(self, N):
        """
        Create an object representing all possible mappings from 
        2D grid points to {0, 1}. 
        :param N: X-space samples are N by N grid in [0, 1)**2
        """
        self.grid_x = generate_all_X_space_samples_np(N)
        self.h_size = 2 ** (N**2)
        
    def size(self):
        """
        Total number of possible mappings.
        
        Note this tend to be really large number for any
        respectable N.
        """
        return self.h_size

In [24]:
complete_model = CompleteDiscrete2DBinaryMapping(10)
print("We are going to build {} different mappings."
       .format(complete_model.size()))

We are going to build 1267650600228229401496703205376 different mappings.


In [0]:
# To be specific, we just need to implement such a function
def predict_according_to_hypothesis(X, hypothesis_id):
    """
    :param X: a data has 2 attributes
    :param hypothesis_id: a number in 0..1267650600228229401496703205376 
        (e.g. N=10)
    NOTE: for stand-alone function (not belonging to any class,
        "unbounded" is the technical term), we don't have the "self"
        in the first place in the input argument list.    
    """
    y = 0 # or 1
    return y

In [26]:
# To compute the nearest neighbour, 
# please experiment with the following code.
X_np = generate_all_X_space_samples_np(2)
print("2D points")
print(X_np)
Xin = np.array((1, 2))
print("Input X")
print(Xin)
print("Difference")
print(X_np - Xin)

2D points
[[0 0]
 [1 0]
 [0 1]
 [1 1]]
Input X
[1 2]
Difference
[[-1 -2]
 [ 0 -2]
 [-1 -1]
 [ 0 -1]]


In [0]:

# To compute the nearest neighbour
diff = X_np - Xin
diff_square = diff ** 2 # each element
diff_norm2 = diff_square.sum(axis=1) # summing up every row, so now we have 
# N**2 distances (same number of X-rows) and need only to find the 
# smallest one.

In [28]:
print("The index of the nearest x-grid point is {}"
      .format(np.argmin(diff_norm2))) # argmin returns the index of the 
# smallest element in an array (take care and read doc for multi-dim arrays)

The index of the nearest x-grid point is 3


In [29]:
# to convert a number to binary format
print("{:b}".format(35))
# to specify the number of bits
print("{:9b}".format(35))
# to specify the number of bits and fill unused bits with 0
print("{:09b}".format(35))
# to specify the number of bits and fill unused bits with 0
# and finally take out the 3rd bit
print("{:09b}".format(35) [2])

# given N, build the "formatting" string (a meta string you use to 
# format other strings
N=3
print("{:0" + str(N**2) + "b}") # "+" concatenates strings

100011
   100011
000100011
0
{:09b}


In [0]:
class CompleteDiscrete2DBinaryMapping(object):
    """
    An exhaustive representation of 2D X space to binary targets.
    The 2D space is represented using discrete grid points.
    """
    def __init__(self, N):
        """
        Create an object representing all possible mappings from 
        2D grid points to {0, 1}. 
        :param N: X-space samples are N by N grid in [0, 1)**2
        """
        self.grid_x = generate_all_X_space_samples_np(N)
        self.dof = N ** 2 # the degrees of freedom is eaqual to the number
        # of grid points at which you can freely choose {0/1} as the 
        # target value. DoF reduces as you start observing data (when you
        # observe the target value at a point, you lose the freedom of
        # setting it to arbitrary values)
        self.h_size = 2 ** self.dof
        
    def size(self):
        """
        Total number of possible mappings.
        
        Note this tend to be really large number for any
        respectable N.
        """
        return self.h_size
    
    def predict_according_to_hypothesis(self, X, hypothesis_id):
        """
        Note, when implement as class method, don't miss "self"
        :param X: a data has 2 attributes
        :param hypothesis_id: a number in 0..1267650600228229401496703205376 
            (e.g. N=10)
        """
        X = np.array(X) # make the input format more flexible, e.g.
        # you can use [0, 2] (Python list), or (0, 1) (Python tuple)
        d = ((self.grid_x - X)**2).sum(axis=1)
        bit_id = np.argmin(d)
        format_string = "{:0" + str(self.dof) + "b}"
        y = int(format_string.format(hypothesis_id) [bit_id])
        return y

In [31]:
complete_model = CompleteDiscrete2DBinaryMapping(10)
print("We are going to build {} different mappings."
       .format(complete_model.size()))

We are going to build 1267650600228229401496703205376 different mappings.


In [0]:

class CompleteDiscrete2DBinaryMapping(object):
    def __init__(self, N):
        self.grid_x = generate_all_X_space_samples_np(N)
        self.dof = N ** 2 # the degrees of freedom is eaqual to the number
        # of grid points at which you can freely choose {0/1} as the 
        # target value. DoF reduces as you start observing data (when you
        # observe the target value at a point, you lose the freedom of
        # setting it to arbitrary values)
        self.h_size = 2 ** self.dof
        self.inconsistent_hypotheses = []
        
    def size(self):
        return self.h_size
    
    def predict_according_to_hypothesis(self, X, hypothesis_id):
        X = np.array(X)
        d = ((self.grid_x - X)**2).sum(axis=1)
        bit_id = np.argmin(d)
        format_string = "{:0" + str(self.dof**2) + "b}"
        y = int(format_string.format(hypothesis_id) [bit_id])
        return y
    
    # Let add a `fit` method
    def fit(self, X, Y): 
        """
        :param X: [M x 2] training data
        :param Y: [M] labels
        """
        # Let's check consistency for each training data and each hypothesis 
        for hid in range(self.h_size):
            for x_, y_ in zip(X, Y): 
                # be careful if the training set contains only 1 sample!
                # zip is literally zipping two "iterables" so the zipped object
                # yield multiple elements in each iteration.
                pred = self.predict_according_to_hypothesis(x_, hid)
                if pred != y_:
                    if hid not in self.inconsistent_hypotheses:
                        self.inconsistent_hypotheses.append(hid)
                    break # we have determined this hid is bad and no need
                    # to continue
        
        
    def predict_trained(self, X):
        return [
            self.predict_according_to_hypothesis(X, hid)
            for hid in range(self.h_size)
            if hid not in self.inconsistent_hypotheses
        ]

In [0]:

# Test using the example we have seen in class
complete_model = CompleteDiscrete2DBinaryMapping(3)
X_trn = [
    (0, 2),
    (1, 2),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 1),
]
Y_trn = [0, 0, 1, 1, 1, 1]
complete_model.fit(X_trn, Y_trn)

In [34]:
# Let us use the model to predict
complete_model.predict_trained((0, 2))

[]

In [0]:
# A Simple Linear Model Family
import numpy as np
class LinearHypothesisSpace:
    def __init__(self, quant_num=3):
        self.quant_num = quant_num
        grid_x0, grid_x1 = np.meshgrid(np.arange(self.quant_num),
                                       np.arange(self.quant_num))
        grid_x0 = grid_x0.flatten()
        grid_x1 = grid_x1.flatten()
        self.grid_x = np.stack([grid_x0, grid_x1]).T

        eps_angle = np.pi / 18
        angles = np.arange(0, np.pi, eps_angle)
        self.hypotheses = np.zeros((2 * len(angles), self.quant_num ** 2),
                                   dtype=np.int)
        x0 = grid_x0 - (quant_num - 1) / 2
        x1 = grid_x1 - (quant_num - 1) / 2
        for i, th in enumerate(angles):
            w = min(np.tan(th), 9999)
            # ** PREDICTION BY INDIVIDUAL HYPOTHESIS **
            ya = (x0 * w - x1 > 0).astype(np.int)
            yb = 1 - ya
            self.hypotheses[2 * i, :] = ya
            self.hypotheses[2 * i + 1, :] = yb
        self.sele_hypothesis_id = None

    def fit(self, x, y):
        x_ind = x[:, 0] + self.quant_num * x[:, 1]
        pred_trn = self.hypotheses[:, x_ind]
        accu_trn = pred_trn == y[np.newaxis, :]  # type: np.ndarray
        accu_trn_n = accu_trn.astype(np.float).sum(axis=1)
        self.sele_hypothesis_id = np.argmax(accu_trn_n)

    def predict_all_X(self, hypothesis_id=-1):
        h = self.hypotheses[self.sele_hypothesis_id] \
            if hypothesis_id == -1 \
            else self.hypotheses[hypothesis_id]
        return self.grid_x, h

In [0]:
linear_model0 = LinearHypothesisSpace(3)
X_trn = np.array([
    (0, 2),
    (1, 2),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 1),
])
Y_trn = np.array([0, 0, 1, 1, 1, 1])
linear_model0.fit(X_trn, Y_trn)

In [0]:
X_all, y_all = linear_model0.predict_all_X()

In [0]:
# Finally, let us visualise the model behaviour, we will us an interactive 
# visualision tool.

# NOTE drawing graphs is one noticeable difference between running your
# Python notebook on cloud (where the computers don't have screens and have
# to deliver graphics objects to your browser to render on YOUR screen), and 
# on local computer (where graphics display natively using graph interface 
# provided by your local OS). So we make a bit configuration here. 
#
# If the graphs don't work on your computer, try on colab, or you can 
# change to classical matplotlib library, which is easier to make working.


I_AM_RUNNING_THIS_NOTEBOOK_ON_MY_OWN_COMPUTER = False
COLAB = not I_AM_RUNNING_THIS_NOTEBOOK_ON_MY_OWN_COMPUTER

In [39]:
if COLAB: # We need to upgrade plotly to 4.0 for it to work with colab
    # [as of July 2019] this will obsolete soon when Google upgrades colab
    !pip install plotly --upgrade
    # Peform the same on your own computer if encountering issues, but only
    # do it once and for all. colab is a virtual machine, so you need to
    # perform the upgrading each time restarting a session.

     |████████████████████████████████| 6.8MB 4.7MB/s 
  Found existing installation: plotly 3.6.1
    Uninstalling plotly-3.6.1:
      Successfully uninstalled plotly-3.6.1


In [40]:
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Scatter(
        x=X_all[:, 0], 
        y=X_all[:, 1], 
        marker_color=y_all,
        marker_size=12,
        marker_line_width=2,
        mode="markers")],
    layout_title_text="Prediction on a Discretised 2D X-Space"
)
if COLAB:
    fig.show(renderer="colab")
else:
    fig.show()

In [41]:
# Now we can handle decently sized (2D discrete) data space
hypothesis_id = 21 # we havn't trained the model, so need to specify which hypo
# we want to check
linear_model1 = LinearHypothesisSpace(50)
X_all, y_all = linear_model1.predict_all_X(hypothesis_id)
fig = go.Figure(
    data=[go.Scatter(
        x=X_all[:, 0], 
        y=X_all[:, 1], 
        marker_color=y_all,
        marker_size=12,
        marker_line_width=2,
        mode="markers")],
    layout_title_text="Prediction on a Discretised 2D X-Space"
)
if COLAB:
    fig.show(renderer="colab")
else:
    fig.show()

# **Model Complexity**

In [0]:
# Environment and constant preparation
import numpy as np
from sklearn.datasets import load_iris
import plotly.graph_objects as go
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

COLAB = False
IRIS_EXPERIMENT_X_SPACE_QUANTISATION_BIN_NUM = 50 # self-interpretation

def generate_all_X_space_normalised_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    return np.stack([X0.flatten(), X1.flatten()]).T / N

In [0]:
# load the data
iris_db = load_iris()
all_x = generate_all_X_space_normalised_samples_np(
    IRIS_EXPERIMENT_X_SPACE_QUANTISATION_BIN_NUM)

In [0]:

# BEGIN Data Inspection

In [45]:
# load_iris returns an object `iris_db`, but for now, we don't have much 
# information on the object. We usually start studying unknown objects
# in one of the following two steps.

# 1. check what is its `type`, and see what the author of the object template 
# (the class) has to say
print(type(iris_db))

<class 'sklearn.utils.Bunch'>


In [0]:

# Depending on your environment, the result should be something like
# <class 'sklearn.utils.Bunch'>
# "Bunch" is the name of the class, living in the "utils" sub-module
# which, in turn, is in the "sklearn" library.

# Now let's get some help of the class. (most popular libraries
# are well documented)
iris_db?

In [47]:
# As the doc-string doesn't provide much information of this object.
# let's try method
# 2. duck-typing: check how the object "quacks" and "walks"
dir(iris_db) # dir() lists methods / attributes of an object.

# you may find "DESCR" to be useful, try to print it out.

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [48]:
# The most interesting parts of the dataset object are
# `data` and `target` of course. Let's check `data`.
type(iris_db.data), type(iris_db.target)

(numpy.ndarray, numpy.ndarray)

In [49]:
# We are familiar with numpy arrays. Perform some standard checks
print(iris_db.data.shape, iris_db.target.shape)

(150, 4) (150,)


In [50]:
# This looks like 150 data samples with 150 corresponding labels.
print(iris_db.data[:10], iris_db.target[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]] [0 0 0 0 0 0 0 0 0 0]


In [0]:

# END of Data Inspection

In [0]:
# just to save typing
X, y = iris_db.data, iris_db.target

In [0]:
# So the idea becomes: 
# for each training sample, (let us identify the training sample 
# using an index i), 
# - include the data[i] and the target[i] in the subset, 
#   if target[i] is 0 or 1.

# translating the idea into a program
X_sub = []
y_sub = []
for i in range(len(iris_db.data)): 
    # [EXERCISE] What does range(len(...)) do 
    # for an ensemble object? 
    if iris_db.target[i] == 0 or iris_db.target[i] == 1:
        X_sub.append(iris_db.data[i])
        y_sub.append(iris_db.target[i])

In [54]:
# Check what we have obtained.
print(X_sub[0:5])
print(y_sub[0:5])

[array([5.1, 3.5, 1.4, 0.2]), array([4.9, 3. , 1.4, 0.2]), array([4.7, 3.2, 1.3, 0.2]), array([4.6, 3.1, 1.5, 0.2]), array([5. , 3.6, 1.4, 0.2])]
[0, 0, 0, 0, 0]


In [55]:
# We can organise X_sub and y_sub as numpy arrays.
# (so we can access the elements more easily)
X_sub = np.array(X_sub)
y_sub = np.array(y_sub)
print(X_sub[0:5])
print(y_sub[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [0]:
# Translating the idea into a program
X_sub = []
y_sub = []
for x_, y_ in zip(iris_db.data, iris_db.target): 
    # [EXERCISE] Print the iteration variables in a zipped list.
    # I.e. construct two lists L1 and L2, and make a for loop
    # over "a, b in zip(L1, L2)", check the values of a and b.
    if y_ == 0 or y_ == 1:
        X_sub.append(x_)
        y_sub.append(y_)
X_sub = np.array(X_sub)
y_sub = np.array(y_sub)

In [0]:
# (*) We can use more "descriptive", less "instructive" construction
X_sub = np.array([x_ for x_, y_ in zip(iris_db.data, iris_db.target)
                  if y_ == 0 or y_ == 1])
y_sub = np.array([y_ for x_, y_ in zip(iris_db.data, iris_db.target)
                  if y_ == 0 or y_ == 1])

In [0]:

X_sub = X[(y==0) + (y==1)] # "+" for boolean OR
y_sub = y[(y==0) + (y==1)]

# Consolidate following reference to the data
X = X_sub
y = y_sub

In [0]:
X = X[:, :2]

In [0]:
quant_num = IRIS_EXPERIMENT_X_SPACE_QUANTISATION_BIN_NUM

# A grid of cells to store the y-values in each area in
# X-space. 
data_bins = [[[] for a1 in range(quant_num)]
             for a2 in range(quant_num)]

# Decide which bin each training sample belongs to

# 1. We want the smallest value of an attribute to be stored in bin[0]
#    and largest in bin[49] (say, for 50 bins)
attrib0_min_value = X[:,0].min()
attrib0_max_value = X[:,0].max() # perform 0-1 normalisation on attribute 0
X[:, 0] = (X[:, 0] - attrib0_min_value) / (attrib0_max_value - attrib0_min_value)

attrib1_min_value = X[:,1].min()
attrib1_max_value = X[:,1].max()
X[:, 1] = (X[:, 1] - attrib1_min_value) / (attrib1_max_value - attrib1_min_value)

for x_, y_ in zip(X, y):
    attrib0_bin_index = int(round(x_[0] * (quant_num - 1)))
    attrib1_bin_index = int(round(x_[1] * (quant_num - 1)))
    data_bins[attrib0_bin_index][attrib1_bin_index].append(y_)
    # print(attrib0_bin_index, attrib1_bin_index)
    
# now we can arrange the data in a grid
X_quant = []
y_quant = []
for grid_row in range(quant_num):
    for grid_col in range(quant_num):
        this_bin = data_bins[grid_row][grid_col]
        if len(this_bin) > 0:
                X_quant.append((grid_row, grid_col))
                vote = int(round(np.mean(this_bin))) # if more than one y-value
                # has been allocated to this cell (small area in X-space),
                # we let them vote and take the majority.
                y_quant.append(vote)
                
X_quant = np.array(X_quant) / quant_num # (0..1)
y_quant = np.array(y_quant)

In [0]:

X = X_quant
y = y_quant

In [0]:
def preproc_data_for_complexity_experiment_quick(iris_db):
    
    X, y = iris_db.data, iris_db.target
    X = X[(y==0) + (y==1)][:, :2]
    y = y[(y==0) + (y==1)]
    
    # normalise to 0-1
    X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
    return X, y

def quantise_data(X, y, quant_num):
    
    # merge different y-values in the same cell                 
    X = np.round(X  * (quant_num - 1)).astype(np.int)
    data_bins = [[[] for a1 in range(quant_num)]
             for a2 in range(quant_num)]
    for (a1_, a2_), y_ in zip(X, y):
        data_bins[a1_][a2_].append(y_)
    X_quant = []
    y_quant = []
    for grid_row in range(quant_num):
        for grid_col in range(quant_num):
            this_bin = data_bins[grid_row][grid_col]
            if len(this_bin) > 0:
                    X_quant.append((grid_row, grid_col))
                    vote = int(round(np.mean(this_bin))) # if more than one y-value
                    # has been allocated to this cell (small area in X-space),
                    # we let them vote and take the majority.
                    y_quant.append(vote)
    X = np.array(X_quant) / quant_num # (0..1)
    y = np.array(y_quant)
    return X, y

In [0]:
X, y = preproc_data_for_complexity_experiment_quick(iris_db)
# you can comment out the following statement if not wanting quantisation
X, y = quantise_data(X, y, IRIS_EXPERIMENT_X_SPACE_QUANTISATION_BIN_NUM)

In [64]:
layout = go.Layout(
    xaxis=go.layout.XAxis(
        range=[0, 1],
        showgrid=True,
        zeroline=True,
        showline=True,
        gridcolor='#bdbdbd',
        gridwidth=1,
        zerolinecolor='#969696',
        zerolinewidth=2,
        linecolor='#636363',
        linewidth=2,
        mirror=True,
    ),
    yaxis=go.layout.YAxis(
        range=[0, 1],
        showgrid=True,
        zeroline=True,
        showline=True,
        gridcolor='#bdbdbd',
        gridwidth=1,
        zerolinecolor='#969696',
        zerolinewidth=2,
        linecolor='#636363',
        linewidth=2,
        mirror=True,
   ),
   height=600,
   width=600,
)

fig = go.Figure(
    data=[
        go.Scatter(
            x=all_x[:, 0], 
            y=all_x[:, 1], 
            marker_color="rgba(0.7, 0.7, 0.7, 0.3)",
            marker_size=6,
            marker_line_width=2,
            mode="markers",
            name="'All' X Space Samples"),
        go.Scatter(
            x=X[:, 0], 
            y=X[:, 1], 
            marker_color=y,
            marker_size=12,
            marker_line_width=2,
            mode="markers",
            name="Dataset Samples"), 
    ],
    layout=layout,
    layout_title_text="Quantized Simplified Iris Data"
)
if COLAB:
    fig.show(renderer="colab")
else:
    fig.show()

In [0]:
# This is a replica, FYI. The libraries have been imported above.
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [0]:
train_num = 40
noise = 0.15

In [0]:
complex_E_in = []
complex_E_out = [] # we cannot compute this, as we don't have the true concept 
# of Iris data. We can make one up in a later version for experiment. But for now, 
# let us use the evaluation on held-out test data instead. See below complex_E_test.
complex_E_test = []
simple_E_in = []
simple_E_test = []

# We perform multiple rounds of experiments to test the statistics of 
# E_in and E_test for different models / experiment settings.

# Randomly add noise to the data.
rng = np.random.RandomState(42)
noisy_y = np.array([
    y_ if rng.rand() > noise else (1-y_)
    for y_ in y
])
for random_seed in range(500):
    # Randomly split training/test data
    X_train, X_test, y_train, y_test = train_test_split(
        X, noisy_y, train_size=train_num, test_size=len(y)-train_num,
        stratify=noisy_y,
        random_state=random_seed)
    
    # Fit a complex model
    dt_complex = DecisionTreeClassifier(max_depth=100)
    dt_complex.fit(X_train, y_train)
    
    # Record training and test error
    pred_on_X_train = dt_complex.predict(X_train)
    E_in = np.sum(pred_on_X_train != y_train) / len(y_train) # error rate
    complex_E_in.append(E_in)
    pred_on_X_test = dt_complex.predict(X_test)
    E_test = np.sum(pred_on_X_test != y_test) / len(y_test) # error rate
    complex_E_test.append(E_test)
    
    # Fit a simple model
    dt_simple = DecisionTreeClassifier(max_depth=2)
    dt_simple.fit(X_train, y_train)
    
    # Record training and test error
    pred_on_X_train = dt_simple.predict(X_train)
    E_in = np.sum(pred_on_X_train != y_train) / len(y_train) # error rate
    simple_E_in.append(E_in)
    pred_on_X_test = dt_simple.predict(X_test)
    E_test = np.sum(pred_on_X_test != y_test) / len(y_test) # error rate
    simple_E_test.append(E_test)

complex_E_in = np.array(complex_E_in)
complex_E_test = np.array(complex_E_test)
simple_E_in = np.array(simple_E_in)
simple_E_test = np.array( simple_E_test)

In [68]:
print("Complex Tree average E_in mean {:.3f}, std {:.3f}"
      .format(complex_E_in.mean(), complex_E_in.std()))
print("Complex Tree average E_out mean {:.3f}, std {:.3f}"
      .format(complex_E_test.mean(), complex_E_test.std()))
abs_diff = np.abs(complex_E_in - complex_E_test)
print("Complex Tree average |E_out - E_in| mean {:.3f}, std {:.3f}"
      .format(abs_diff.mean(), abs_diff.std()))

print("Simple Tree average E_in mean {:.3f}, std {:.3f}"
      .format(simple_E_in.mean(), simple_E_in.std()))
print("Simple Tree average E_out mean {:.3f}, std {:.3f}"
      .format(simple_E_test.mean(), simple_E_test.std()))
abs_diff = np.abs(simple_E_in - simple_E_test)
print("Simple Tree average |E_out - E_in| mean {:.3f}, std {:.3f}"
      .format(abs_diff.mean(), abs_diff.std()))

Complex Tree average E_in mean 0.000, std 0.000
Complex Tree average E_out mean 0.389, std 0.070
Complex Tree average |E_out - E_in| mean 0.389, std 0.070
Simple Tree average E_in mean 0.177, std 0.045
Simple Tree average E_out mean 0.289, std 0.061
Simple Tree average |E_out - E_in| mean 0.119, std 0.072
