<a href="https://colab.research.google.com/github/haishan-shi/A1/blob/master/NativeLearning_Samples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Represent_All_X_Samples.

In [0]:
def generate_all_X_space_samples():
    """
    As the function name shows,  here we want to return the 
    complete set of possible X values. The straightforward 
    implementation of the X-space is a list of tuples. Let us 
    consider a simple range: the integers from 0 to N-1, and 
    use this range for both dimensions. Say N=3, we want to 
    generate X-samples as
    [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
        (2, 0),
        (2, 1),
        (2, 2),
    ]
    
    For small N, we can explicitly write out the list, but we need 
    a program to generate such a list for arbitrary N:
    """
    
    # Let's make an empty list
    X_space = []
    
    # Study the elements in the example list, and fill up our
    # X_space, e.g. by
    X_space.append((0, 0)) # A sample in X is a tuple, so we use 
    # a pair of parentheses, i.e. the input to the "append" function
    # is "(0, 0)", not "0, 0", which will be interpreted as 2 inputs.
    X_space.append((0, 1))
    X_space.append((0, 2))
    # ... you can complete the rest if you wish, but better read on.
    # we will use smarter methods.
    
    # Last but note least, 
    return X_space

In [5]:
X_space = generate_all_X_space_samples()
print(X_space)

[(0, 0), (0, 1), (0, 2)]


In [0]:
def generate_all_X_space_samples():
    """
    We will use loops to generate the tuples!
    """
    
    # Let's make an empty list
    X_space = []
    
    # Simple observation shows the first 3 tuples are (0, j)
    # and j is running from 0 to 3 (exclusive, Python convention)
    
    # This is the perfect case to use a for-loop, so we can write the
    # list building program this way:
    
    # for j in range(3):
    #     X_space.append((0, j))
    # for j in range(3):
    #     X_space.append((1, j))
    # for j in range(3):
    #     X_space.append((2, j))
    
    # You may have noticed, the first element in each tuple in those
    # loops runs from 0 to 3 (exclusive) as well, and can also be
    # managed by a loop
    for i in range(3):
        for j in range(3):
            X_space.append((i, j))
    return X_space

In [7]:
X_space = generate_all_X_space_samples()
print(X_space)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


In [8]:

# 1. building list by appending one element each time
my_list_a = []
for i in range(5):
    my_list_a.append(i**2) # square
print("List-a of Sqr for [0, 5):", my_list_a)

# 2. Write the message above naturally as python code
my_list_b = [i**2 for i in range(5)] # Bracket [..] to construct a list
print("List-b of Sqr for [0, 5):", my_list_b)

List-a of Sqr for [0, 5): [0, 1, 4, 9, 16]
List-b of Sqr for [0, 5): [0, 1, 4, 9, 16]


In [9]:
# 3. Powerful generator
# The element object can be complex object. 
# The []-generating loop can be nested.
# The generation process can be conditioned, too.

my_list_c = [(j, j + i**2) for i in range(10)
             if i % 2 == 0
             for j in range(100, 600, 100)
             if j != 300]
print(my_list_c)

[(100, 100), (200, 200), (400, 400), (500, 500), (100, 104), (200, 204), (400, 404), (500, 504), (100, 116), (200, 216), (400, 416), (500, 516), (100, 136), (200, 236), (400, 436), (500, 536), (100, 164), (200, 264), (400, 464), (500, 564)]


In [0]:
def generate_all_X_space_samples(N):
    """
    Generate complete sample of X-space
    :param N: Discrete X-space dimension size. The size is homogeneous
      in all dimensions.
    :type N: int
    """
    
    return [(i, j) for i in range(N)
            for j in range(N)]

In [11]:

X = generate_all_X_space_samples(3)
print("There are {} samples in X-space.".format(len(X))) # {}-format
# is used to inject some information from variables to a string.
print("All samples:\n\t", X) # \n: new line, \t indent

# You can also investigate using multiple print's
for sample_id in range(len(X)): # Try to figure out the construction
    print("Sampe {}: {}".format(sample_id, X[sample_id]))
    
# You can use [:] indexing to conveniently check a subset of data samples
print("Sample 1-5 (exc):", X[1:5])
# [:End] means start from 0
print("Sample 0-3 (exc):", X[:3])
# Similarly, [Start:] means until the end
print("Sample 3-Last (inc):", X[3:])
# You can use -i (<0 index) to represent "reversing from the end"
print("Last Sample:", X[-1])
print("Sample 3-Last (exc):", X[3:-1])

There are 9 samples in X-space.
All samples:
	 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Sampe 0: (0, 0)
Sampe 1: (0, 1)
Sampe 2: (0, 2)
Sampe 3: (1, 0)
Sampe 4: (1, 1)
Sampe 5: (1, 2)
Sampe 6: (2, 0)
Sampe 7: (2, 1)
Sampe 8: (2, 2)
Sample 1-5 (exc): [(0, 1), (0, 2), (1, 0), (1, 1)]
Sample 0-3 (exc): [(0, 0), (0, 1), (0, 2)]
Sample 3-Last (inc): [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Last Sample: (2, 2)
Sample 3-Last (exc): [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1)]


In [0]:
# Let us use the numpy library
import numpy as np # the "as" is optional and to save typing

def generate_all_X_space_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    
    # Let's make an empty list
    X_space = np.zeros((N**2, 2)) # the 
    
    # Loop is similar to that in Round2
    # except that all samples are created at the
    # beginning, and we now use an index to loop over them
    index = 0
    for i in range(N):
        for j in range(N):
            X_space[index][0] = i
            X_space[index][1] = j
            index += 1
    return X_space

In [13]:
X_np = generate_all_X_space_samples_np(3)
print(X_np)
print(type(X_np)) # Note the type is a np-array
# Check out a sample
i = 3
print("An X-Sample[{}]:{}".format(i, X_np[i]))
# Check attribute-0 for all samples
j = 0
print("X-Attribute[{}]:{}".format(j, X_np[:, j]))
# [:, 0]: take from all (:) samples, the attribute-0

[[0. 0.]
 [0. 1.]
 [0. 2.]
 [1. 0.]
 [1. 1.]
 [1. 2.]
 [2. 0.]
 [2. 1.]
 [2. 2.]]
<class 'numpy.ndarray'>
An X-Sample[3]:[1. 0.]
X-Attribute[0]:[0. 0. 0. 1. 1. 1. 2. 2. 2.]


In [0]:
def scale_X_to_0_1(X, N):
    """
    Get a new list scaling the elements in X by 1/N.
    """
    new_list = []
    for x in X: # you can iterate over each element (a tuple in x)
        # now x is one data sample in X, such as (0, 2)
        new_list.append((x[0]/N, x[1]/N))
    return new_list

In [15]:
X = generate_all_X_space_samples(5)
X1 = scale_X_to_0_1(X, 5)
print(X1)

[(0.0, 0.0), (0.0, 0.2), (0.0, 0.4), (0.0, 0.6), (0.0, 0.8), (0.2, 0.0), (0.2, 0.2), (0.2, 0.4), (0.2, 0.6), (0.2, 0.8), (0.4, 0.0), (0.4, 0.2), (0.4, 0.4), (0.4, 0.6), (0.4, 0.8), (0.6, 0.0), (0.6, 0.2), (0.6, 0.4), (0.6, 0.6), (0.6, 0.8), (0.8, 0.0), (0.8, 0.2), (0.8, 0.4), (0.8, 0.6), (0.8, 0.8)]


In [16]:
# On te other hand, operating on numpy array is much easier
X_np = generate_all_X_space_samples_np(5)
X1_np = X_np/5
print(X1_np)

[[0.  0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.6]
 [0.  0.8]
 [0.2 0. ]
 [0.2 0.2]
 [0.2 0.4]
 [0.2 0.6]
 [0.2 0.8]
 [0.4 0. ]
 [0.4 0.2]
 [0.4 0.4]
 [0.4 0.6]
 [0.4 0.8]
 [0.6 0. ]
 [0.6 0.2]
 [0.6 0.4]
 [0.6 0.6]
 [0.6 0.8]
 [0.8 0. ]
 [0.8 0.2]
 [0.8 0.4]
 [0.8 0.6]
 [0.8 0.8]]


In [17]:
%timeit X1 = scale_X_to_0_1(X, 5)

100000 loops, best of 3: 6.23 µs per loop


In [18]:
%timeit X1 = X1_np = X_np/5

The slowest run took 36.01 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.11 µs per loop


In [0]:
def generate_all_X_space_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    # We will have the following for N=3
    # X0:      X1:
    # 0 1 2    0 0 0
    # 0 1 2    1 1 1
    # 0 1 2    2 2 2
    
    # X0, if "flattened", becomes
    # 0 1 2 0 1 2 0 1 2
    
    # flattened X0 and X1 if "stacked" becomes
    # [[0 1 2 0 1 2 0 1 2
    #  [0 0 0 1 1 1 2 2 2]]
    
    # The following matrix, 
    # [[a b c]
    #  [d e f]]
    # if "transposed" (numpy operator "T"), becomes
    # [[a d]
    #  [b e]
    #  [c f]]
    return np.stack([X0.flatten(), X1.flatten()]).T

In [20]:
print(generate_all_X_space_samples_np(3))

[[0 0]
 [1 0]
 [2 0]
 [0 1]
 [1 1]
 [2 1]
 [0 2]
 [1 2]
 [2 2]]


In [21]:
%timeit generate_all_X_space_samples_np(500)

The slowest run took 8.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 3.46 ms per loop


In [22]:
%timeit generate_all_X_space_samples(500)

10 loops, best of 3: 43.9 ms per loop


In [0]:

# Finally, we can make version that includes the normalisation 
# (1/N) in the construction
def generate_all_X_space_normalised_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    return np.stack([X0.flatten(), X1.flatten()]).T / N

In [24]:
print(generate_all_X_space_samples_np(3))

[[0 0]
 [1 0]
 [2 0]
 [0 1]
 [1 1]
 [2 1]
 [0 2]
 [1 2]
 [2 2]]


In [25]:
X = generate_all_X_space_samples(5)
X1 = scale_X_to_0_1(X, 5)
print(X1)

[(0.0, 0.0), (0.0, 0.2), (0.0, 0.4), (0.0, 0.6), (0.0, 0.8), (0.2, 0.0), (0.2, 0.2), (0.2, 0.4), (0.2, 0.6), (0.2, 0.8), (0.4, 0.0), (0.4, 0.2), (0.4, 0.4), (0.4, 0.6), (0.4, 0.8), (0.6, 0.0), (0.6, 0.2), (0.6, 0.4), (0.6, 0.6), (0.6, 0.8), (0.8, 0.0), (0.8, 0.2), (0.8, 0.4), (0.8, 0.6), (0.8, 0.8)]


# Represent all possible X-y relations

In [0]:
# Let us first prepare the X-space as discrete samples as above. 
# And before we start building all the possible X-y mappings. 
# It is sensible to have an idea about how many such 
# mappings we are going to consider.

# So here is our first attempt of making the object template 
# of the all-inclusive mapping representation.
class CompleteDiscrete2DBinaryMapping(object):
    """
    An exhaustive representation of 2D X space to binary targets.
    The 2D space is represented using discrete grid points.
    """
    def __init__(self, N):
        """
        Create an object representing all possible mappings from 
        2D grid points to {0, 1}. 
        :param N: X-space samples are N by N grid in [0, 1)**2
        """
        self.grid_x = generate_all_X_space_samples_np(N)
        self.h_size = 2 ** (N**2)
        
    def size(self):
        """
        Total number of possible mappings.
        
        Note this tend to be really large number for any
        respectable N.
        """
        return self.h_size

In [27]:
complete_model = CompleteDiscrete2DBinaryMapping(10)
print("We are going to build {} different mappings."
       .format(complete_model.size()))

We are going to build 1267650600228229401496703205376 different mappings.


In [0]:
# To be specific, we just need to implement such a function
def predict_according_to_hypothesis(X, hypothesis_id):
    """
    :param X: a data has 2 attributes
    :param hypothesis_id: a number in 0..1267650600228229401496703205376 
        (e.g. N=10)
    NOTE: for stand-alone function (not belonging to any class,
        "unbounded" is the technical term), we don't have the "self"
        in the first place in the input argument list.    
    """
    y = 0 # or 1
    return y

In [29]:
# To compute the nearest neighbour, 
# please experiment with the following code.
X_np = generate_all_X_space_samples_np(2)
print("2D points")
print(X_np)
Xin = np.array((1, 2))
print("Input X")
print(Xin)
print("Difference")
print(X_np - Xin)

2D points
[[0 0]
 [1 0]
 [0 1]
 [1 1]]
Input X
[1 2]
Difference
[[-1 -2]
 [ 0 -2]
 [-1 -1]
 [ 0 -1]]


In [0]:

# To compute the nearest neighbour
diff = X_np - Xin
diff_square = diff ** 2 # each element
diff_norm2 = diff_square.sum(axis=1) # summing up every row, so now we have 
# N**2 distances (same number of X-rows) and need only to find the 
# smallest one.

In [31]:
print("The index of the nearest x-grid point is {}"
      .format(np.argmin(diff_norm2))) # argmin returns the index of the 
# smallest element in an array (take care and read doc for multi-dim arrays)

The index of the nearest x-grid point is 3


In [32]:
# to convert a number to binary format
print("{:b}".format(35))
# to specify the number of bits
print("{:9b}".format(35))
# to specify the number of bits and fill unused bits with 0
print("{:09b}".format(35))
# to specify the number of bits and fill unused bits with 0
# and finally take out the 3rd bit
print("{:09b}".format(35) [2])

# given N, build the "formatting" string (a meta string you use to 
# format other strings
N=3
print("{:0" + str(N**2) + "b}") # "+" concatenates strings

100011
   100011
000100011
0
{:09b}


In [0]:
class CompleteDiscrete2DBinaryMapping(object):
    """
    An exhaustive representation of 2D X space to binary targets.
    The 2D space is represented using discrete grid points.
    """
    def __init__(self, N):
        """
        Create an object representing all possible mappings from 
        2D grid points to {0, 1}. 
        :param N: X-space samples are N by N grid in [0, 1)**2
        """
        self.grid_x = generate_all_X_space_samples_np(N)
        self.dof = N ** 2 # the degrees of freedom is eaqual to the number
        # of grid points at which you can freely choose {0/1} as the 
        # target value. DoF reduces as you start observing data (when you
        # observe the target value at a point, you lose the freedom of
        # setting it to arbitrary values)
        self.h_size = 2 ** self.dof
        
    def size(self):
        """
        Total number of possible mappings.
        
        Note this tend to be really large number for any
        respectable N.
        """
        return self.h_size
    
    def predict_according_to_hypothesis(self, X, hypothesis_id):
        """
        Note, when implement as class method, don't miss "self"
        :param X: a data has 2 attributes
        :param hypothesis_id: a number in 0..1267650600228229401496703205376 
            (e.g. N=10)
        """
        X = np.array(X) # make the input format more flexible, e.g.
        # you can use [0, 2] (Python list), or (0, 1) (Python tuple)
        d = ((self.grid_x - X)**2).sum(axis=1)
        bit_id = np.argmin(d)
        format_string = "{:0" + str(self.dof) + "b}"
        y = int(format_string.format(hypothesis_id) [bit_id])
        return y

In [36]:
complete_model = CompleteDiscrete2DBinaryMapping(10)
print("We are going to build {} different mappings."
       .format(complete_model.size()))

We are going to build 1267650600228229401496703205376 different mappings.


In [0]:

class CompleteDiscrete2DBinaryMapping(object):
    def __init__(self, N):
        self.grid_x = generate_all_X_space_samples_np(N)
        self.dof = N ** 2 # the degrees of freedom is eaqual to the number
        # of grid points at which you can freely choose {0/1} as the 
        # target value. DoF reduces as you start observing data (when you
        # observe the target value at a point, you lose the freedom of
        # setting it to arbitrary values)
        self.h_size = 2 ** self.dof
        self.inconsistent_hypotheses = []
        
    def size(self):
        return self.h_size
    
    def predict_according_to_hypothesis(self, X, hypothesis_id):
        X = np.array(X)
        d = ((self.grid_x - X)**2).sum(axis=1)
        bit_id = np.argmin(d)
        format_string = "{:0" + str(self.dof**2) + "b}"
        y = int(format_string.format(hypothesis_id) [bit_id])
        return y
    
    # Let add a `fit` method
    def fit(self, X, Y): 
        """
        :param X: [M x 2] training data
        :param Y: [M] labels
        """
        # Let's check consistency for each training data and each hypothesis 
        for hid in range(self.h_size):
            for x_, y_ in zip(X, Y): 
                # be careful if the training set contains only 1 sample!
                # zip is literally zipping two "iterables" so the zipped object
                # yield multiple elements in each iteration.
                pred = self.predict_according_to_hypothesis(x_, hid)
                if pred != y_:
                    if hid not in self.inconsistent_hypotheses:
                        self.inconsistent_hypotheses.append(hid)
                    break # we have determined this hid is bad and no need
                    # to continue
        
        
    def predict_trained(self, X):
        return [
            self.predict_according_to_hypothesis(X, hid)
            for hid in range(self.h_size)
            if hid not in self.inconsistent_hypotheses
        ]

In [0]:

# Test using the example we have seen in class
complete_model = CompleteDiscrete2DBinaryMapping(3)
X_trn = [
    (0, 2),
    (1, 2),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 1),
]
Y_trn = [0, 0, 1, 1, 1, 1]
complete_model.fit(X_trn, Y_trn)

In [39]:
# Let us use the model to predict
complete_model.predict_trained((0, 2))

[]

In [0]:
# A Simple Linear Model Family
import numpy as np
class LinearHypothesisSpace:
    def __init__(self, quant_num=3):
        self.quant_num = quant_num
        grid_x0, grid_x1 = np.meshgrid(np.arange(self.quant_num),
                                       np.arange(self.quant_num))
        grid_x0 = grid_x0.flatten()
        grid_x1 = grid_x1.flatten()
        self.grid_x = np.stack([grid_x0, grid_x1]).T

        eps_angle = np.pi / 18
        angles = np.arange(0, np.pi, eps_angle)
        self.hypotheses = np.zeros((2 * len(angles), self.quant_num ** 2),
                                   dtype=np.int)
        x0 = grid_x0 - (quant_num - 1) / 2
        x1 = grid_x1 - (quant_num - 1) / 2
        for i, th in enumerate(angles):
            w = min(np.tan(th), 9999)
            # ** PREDICTION BY INDIVIDUAL HYPOTHESIS **
            ya = (x0 * w - x1 > 0).astype(np.int)
            yb = 1 - ya
            self.hypotheses[2 * i, :] = ya
            self.hypotheses[2 * i + 1, :] = yb
        self.sele_hypothesis_id = None

    def fit(self, x, y):
        x_ind = x[:, 0] + self.quant_num * x[:, 1]
        pred_trn = self.hypotheses[:, x_ind]
        accu_trn = pred_trn == y[np.newaxis, :]  # type: np.ndarray
        accu_trn_n = accu_trn.astype(np.float).sum(axis=1)
        self.sele_hypothesis_id = np.argmax(accu_trn_n)

    def predict_all_X(self, hypothesis_id=-1):
        h = self.hypotheses[self.sele_hypothesis_id] \
            if hypothesis_id == -1 \
            else self.hypotheses[hypothesis_id]
        return self.grid_x, h

In [0]:
linear_model0 = LinearHypothesisSpace(3)
X_trn = np.array([
    (0, 2),
    (1, 2),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 1),
])
Y_trn = np.array([0, 0, 1, 1, 1, 1])
linear_model0.fit(X_trn, Y_trn)

In [0]:
X_all, y_all = linear_model0.predict_all_X()

In [0]:
# Finally, let us visualise the model behaviour, we will us an interactive 
# visualision tool.

# NOTE drawing graphs is one noticeable difference between running your
# Python notebook on cloud (where the computers don't have screens and have
# to deliver graphics objects to your browser to render on YOUR screen), and 
# on local computer (where graphics display natively using graph interface 
# provided by your local OS). So we make a bit configuration here. 
#
# If the graphs don't work on your computer, try on colab, or you can 
# change to classical matplotlib library, which is easier to make working.


I_AM_RUNNING_THIS_NOTEBOOK_ON_MY_OWN_COMPUTER = False
COLAB = not I_AM_RUNNING_THIS_NOTEBOOK_ON_MY_OWN_COMPUTER

In [58]:
if COLAB: # We need to upgrade plotly to 4.0 for it to work with colab
    # [as of July 2019] this will obsolete soon when Google upgrades colab
    !pip install plotly --upgrade
    # Peform the same on your own computer if encountering issues, but only
    # do it once and for all. colab is a virtual machine, so you need to
    # perform the upgrading each time restarting a session.

     |████████████████████████████████| 6.8MB 5.0MB/s 
  Found existing installation: plotly 3.6.1
    Uninstalling plotly-3.6.1:
      Successfully uninstalled plotly-3.6.1


In [0]:
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Scatter(
        x=X_all[:, 0], 
        y=X_all[:, 1], 
        marker_color=y_all,
        marker_size=12,
        marker_line_width=2,
        mode="markers")],
    layout_title_text="Prediction on a Discretised 2D X-Space"
)
if COLAB:
    fig.show(renderer="colab")
else:
    fig.show()

In [0]:
# Now we can handle decently sized (2D discrete) data space
hypothesis_id = 21 # we havn't trained the model, so need to specify which hypo
# we want to check
linear_model1 = LinearHypothesisSpace(50)
X_all, y_all = linear_model1.predict_all_X(hypothesis_id)
fig = go.Figure(
    data=[go.Scatter(
        x=X_all[:, 0], 
        y=X_all[:, 1], 
        marker_color=y_all,
        marker_size=12,
        marker_line_width=2,
        mode="markers")],
    layout_title_text="Prediction on a Discretised 2D X-Space"
)
if COLAB:
    fig.show(renderer="colab")
else:
    fig.show()