<a href="https://colab.research.google.com/github/haishan-shi/A1/blob/master/Represent_All_X_Samples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def generate_all_X_space_samples():
    """
    As the function name shows,  here we want to return the 
    complete set of possible X values. The straightforward 
    implementation of the X-space is a list of tuples. Let us 
    consider a simple range: the integers from 0 to N-1, and 
    use this range for both dimensions. Say N=3, we want to 
    generate X-samples as
    [
        (0, 0),
        (0, 1),
        (0, 2),
        (1, 0),
        (1, 1),
        (1, 2),
        (2, 0),
        (2, 1),
        (2, 2),
    ]
    
    For small N, we can explicitly write out the list, but we need 
    a program to generate such a list for arbitrary N:
    """
    
    # Let's make an empty list
    X_space = []
    
    # Study the elements in the example list, and fill up our
    # X_space, e.g. by
    X_space.append((0, 0)) # A sample in X is a tuple, so we use 
    # a pair of parentheses, i.e. the input to the "append" function
    # is "(0, 0)", not "0, 0", which will be interpreted as 2 inputs.
    X_space.append((0, 1))
    X_space.append((0, 2))
    # ... you can complete the rest if you wish, but better read on.
    # we will use smarter methods.
    
    # Last but note least, 
    return X_space

In [2]:
X_space = generate_all_X_space_samples()
print(X_space)

[(0, 0), (0, 1), (0, 2)]


In [0]:
def generate_all_X_space_samples():
    """
    We will use loops to generate the tuples!
    """
    
    # Let's make an empty list
    X_space = []
    
    # Simple observation shows the first 3 tuples are (0, j)
    # and j is running from 0 to 3 (exclusive, Python convention)
    
    # This is the perfect case to use a for-loop, so we can write the
    # list building program this way:
    
    # for j in range(3):
    #     X_space.append((0, j))
    # for j in range(3):
    #     X_space.append((1, j))
    # for j in range(3):
    #     X_space.append((2, j))
    
    # You may have noticed, the first element in each tuple in those
    # loops runs from 0 to 3 (exclusive) as well, and can also be
    # managed by a loop
    for i in range(3):
        for j in range(3):
            X_space.append((i, j))
    return X_space

In [4]:
X_space = generate_all_X_space_samples()
print(X_space)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


In [8]:

# 1. building list by appending one element each time
my_list_a = []
for i in range(5):
    my_list_a.append(i**2) # square
print("List-a of Sqr for [0, 5):", my_list_a)

# 2. Write the message above naturally as python code
my_list_b = [i**2 for i in range(5)] # Bracket [..] to construct a list
print("List-b of Sqr for [0, 5):", my_list_b)

List-a of Sqr for [0, 5): [0, 1, 4, 9, 16]
List-b of Sqr for [0, 5): [0, 1, 4, 9, 16]


In [9]:
# 3. Powerful generator
# The element object can be complex object. 
# The []-generating loop can be nested.
# The generation process can be conditioned, too.

my_list_c = [(j, j + i**2) for i in range(10)
             if i % 2 == 0
             for j in range(100, 600, 100)
             if j != 300]
print(my_list_c)

[(100, 100), (200, 200), (400, 400), (500, 500), (100, 104), (200, 204), (400, 404), (500, 504), (100, 116), (200, 216), (400, 416), (500, 516), (100, 136), (200, 236), (400, 436), (500, 536), (100, 164), (200, 264), (400, 464), (500, 564)]


In [0]:
def generate_all_X_space_samples(N):
    """
    Generate complete sample of X-space
    :param N: Discrete X-space dimension size. The size is homogeneous
      in all dimensions.
    :type N: int
    """
    
    return [(i, j) for i in range(N)
            for j in range(N)]

In [12]:

X = generate_all_X_space_samples(3)
print("There are {} samples in X-space.".format(len(X))) # {}-format
# is used to inject some information from variables to a string.
print("All samples:\n\t", X) # \n: new line, \t indent

# You can also investigate using multiple print's
for sample_id in range(len(X)): # Try to figure out the construction
    print("Sampe {}: {}".format(sample_id, X[sample_id]))
    
# You can use [:] indexing to conveniently check a subset of data samples
print("Sample 1-5 (exc):", X[1:5])
# [:End] means start from 0
print("Sample 0-3 (exc):", X[:3])
# Similarly, [Start:] means until the end
print("Sample 3-Last (inc):", X[3:])
# You can use -i (<0 index) to represent "reversing from the end"
print("Last Sample:", X[-1])
print("Sample 3-Last (exc):", X[3:-1])

There are 9 samples in X-space.
All samples:
	 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Sampe 0: (0, 0)
Sampe 1: (0, 1)
Sampe 2: (0, 2)
Sampe 3: (1, 0)
Sampe 4: (1, 1)
Sampe 5: (1, 2)
Sampe 6: (2, 0)
Sampe 7: (2, 1)
Sampe 8: (2, 2)
Sample 1-5 (exc): [(0, 1), (0, 2), (1, 0), (1, 1)]
Sample 0-3 (exc): [(0, 0), (0, 1), (0, 2)]
Sample 3-Last (inc): [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
Last Sample: (2, 2)
Sample 3-Last (exc): [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1)]


In [0]:
# Let us use the numpy library
import numpy as np # the "as" is optional and to save typing

def generate_all_X_space_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    
    # Let's make an empty list
    X_space = np.zeros((N**2, 2)) # the 
    
    # Loop is similar to that in Round2
    # except that all samples are created at the
    # beginning, and we now use an index to loop over them
    index = 0
    for i in range(N):
        for j in range(N):
            X_space[index][0] = i
            X_space[index][1] = j
            index += 1
    return X_space

In [14]:
X_np = generate_all_X_space_samples_np(3)
print(X_np)
print(type(X_np)) # Note the type is a np-array
# Check out a sample
i = 3
print("An X-Sample[{}]:{}".format(i, X_np[i]))
# Check attribute-0 for all samples
j = 0
print("X-Attribute[{}]:{}".format(j, X_np[:, j]))
# [:, 0]: take from all (:) samples, the attribute-0

[[0. 0.]
 [0. 1.]
 [0. 2.]
 [1. 0.]
 [1. 1.]
 [1. 2.]
 [2. 0.]
 [2. 1.]
 [2. 2.]]
<class 'numpy.ndarray'>
An X-Sample[3]:[1. 0.]
X-Attribute[0]:[0. 0. 0. 1. 1. 1. 2. 2. 2.]


In [0]:
def scale_X_to_0_1(X, N):
    """
    Get a new list scaling the elements in X by 1/N.
    """
    new_list = []
    for x in X: # you can iterate over each element (a tuple in x)
        # now x is one data sample in X, such as (0, 2)
        new_list.append((x[0]/N, x[1]/N))
    return new_list

In [16]:
X = generate_all_X_space_samples(5)
X1 = scale_X_to_0_1(X, 5)
print(X1)

[(0.0, 0.0), (0.0, 0.2), (0.0, 0.4), (0.0, 0.6), (0.0, 0.8), (0.2, 0.0), (0.2, 0.2), (0.2, 0.4), (0.2, 0.6), (0.2, 0.8), (0.4, 0.0), (0.4, 0.2), (0.4, 0.4), (0.4, 0.6), (0.4, 0.8), (0.6, 0.0), (0.6, 0.2), (0.6, 0.4), (0.6, 0.6), (0.6, 0.8), (0.8, 0.0), (0.8, 0.2), (0.8, 0.4), (0.8, 0.6), (0.8, 0.8)]


In [17]:
# On te other hand, operating on numpy array is much easier
X_np = generate_all_X_space_samples_np(5)
X1_np = X_np/5
print(X1_np)

[[0.  0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.6]
 [0.  0.8]
 [0.2 0. ]
 [0.2 0.2]
 [0.2 0.4]
 [0.2 0.6]
 [0.2 0.8]
 [0.4 0. ]
 [0.4 0.2]
 [0.4 0.4]
 [0.4 0.6]
 [0.4 0.8]
 [0.6 0. ]
 [0.6 0.2]
 [0.6 0.4]
 [0.6 0.6]
 [0.6 0.8]
 [0.8 0. ]
 [0.8 0.2]
 [0.8 0.4]
 [0.8 0.6]
 [0.8 0.8]]


In [18]:
%timeit X1 = scale_X_to_0_1(X, 5)

100000 loops, best of 3: 6.09 µs per loop


In [19]:
%timeit X1 = X1_np = X_np/5

The slowest run took 51.74 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.05 µs per loop


In [0]:
def generate_all_X_space_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    # We will have the following for N=3
    # X0:      X1:
    # 0 1 2    0 0 0
    # 0 1 2    1 1 1
    # 0 1 2    2 2 2
    
    # X0, if "flattened", becomes
    # 0 1 2 0 1 2 0 1 2
    
    # flattened X0 and X1 if "stacked" becomes
    # [[0 1 2 0 1 2 0 1 2
    #  [0 0 0 1 1 1 2 2 2]]
    
    # The following matrix, 
    # [[a b c]
    #  [d e f]]
    # if "transposed" (numpy operator "T"), becomes
    # [[a d]
    #  [b e]
    #  [c f]]
    return np.stack([X0.flatten(), X1.flatten()]).T

In [21]:
print(generate_all_X_space_samples_np(3))

[[0 0]
 [1 0]
 [2 0]
 [0 1]
 [1 1]
 [2 1]
 [0 2]
 [1 2]
 [2 2]]


In [22]:
%timeit generate_all_X_space_samples_np(500)

The slowest run took 4.89 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 3.28 ms per loop


In [23]:
%timeit generate_all_X_space_samples(500)

10 loops, best of 3: 44.2 ms per loop


In [0]:

# Finally, we can make version that includes the normalisation 
# (1/N) in the construction
def generate_all_X_space_normalised_samples_np(N):
    """
    :param N: X-space will be an N by N discrete-valued array
    """
    X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
    return np.stack([X0.flatten(), X1.flatten()]).T / N

In [25]:
print(generate_all_X_space_samples_np(3))

[[0 0]
 [1 0]
 [2 0]
 [0 1]
 [1 1]
 [2 1]
 [0 2]
 [1 2]
 [2 2]]


In [26]:
X = generate_all_X_space_samples(5)
X1 = scale_X_to_0_1(X, 5)
print(X1)

[(0.0, 0.0), (0.0, 0.2), (0.0, 0.4), (0.0, 0.6), (0.0, 0.8), (0.2, 0.0), (0.2, 0.2), (0.2, 0.4), (0.2, 0.6), (0.2, 0.8), (0.4, 0.0), (0.4, 0.2), (0.4, 0.4), (0.4, 0.6), (0.4, 0.8), (0.6, 0.0), (0.6, 0.2), (0.6, 0.4), (0.6, 0.6), (0.6, 0.8), (0.8, 0.0), (0.8, 0.2), (0.8, 0.4), (0.8, 0.6), (0.8, 0.8)]
